swagger: '2.0'
info:
  version: '1.0'
  title: Cultivation income type Controller
  contact: {}
host: 132.145.228.83
basePath: /lending-origination/cultivation-income-type
securityDefinitions: {}
schemes:
- http
consumes:
- application/json
produces:
- application/json
paths:
  /AnRkr:
    post:
      summary: addCultivationIncomeType
      tags:
      - Misc
      operationId: addCultivationIncomeType
      deprecated: false
      produces:
      - application/json;charset=UTF-8
      parameters:
      - name: username
        in: header
        required: true
        type: string
        description: ''
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/addCultivationIncomeTypeRequest'
      responses:
        '201':
          description: Created
          schema:
            $ref: '#/definitions/addCultivationIncomeType'
          examples:
            application/json;charset=UTF-8:
              messages: CREATED.
              value: '1888620'
          headers:
            Date:
              type: string
              default: Thu, 20 Jul 2023 14:31:24 GMT
            Content-Length:
              type: string
              default: '41'
            Connection:
              type: string
              default: keep-alive
            x-content-type-options:
              type: string
              default: nosniff
            x-xss-protection:
              type: string
              default: 1; mode=block
            cache-control:
              type: string
              default: no-cache, no-store, max-age=0, must-revalidate
            pragma:
              type: string
              default: no-cache
            expires:
              type: string
              default: '0'
            x-frame-options:
              type: string
              default: DENY
            x-envoy-upstream-service-time:
              type: string
              default: '19'
  /AnRkr/all:
    get:
      summary: getAllCultivationIncomeType
      tags:
      - Misc
      operationId: getAllCultivationIncomeType
      deprecated: false
      produces:
      - application/json;charset=UTF-8
      parameters: []
      responses:
        '200':
          description: OK
          schema:
            type: array
            default: ''
            items:
              $ref: '#/definitions/getAllCultivationIncomeType'
          headers:
            Date:
              type: string
              default: Thu, 20 Jul 2023 14:31:33 GMT
            Content-Length:
              type: string
              default: '23324'
            Connection:
              type: string
              default: keep-alive
            etag:
              type: string
              default: '"0b6d80234d26cd0828acb7b911fee362d"'
            x-content-type-options:
              type: string
              default: nosniff
            x-xss-protection:
              type: string
              default: 1; mode=block
            cache-control:
              type: string
              default: no-cache, no-store, max-age=0, must-revalidate
            pragma:
              type: string
              default: no-cache
            expires:
              type: string
              default: '0'
            x-frame-options:
              type: string
              default: DENY
            x-envoy-upstream-service-time:
              type: string
              default: '52'
  /AnRkr/161351:
    put:
      summary: updateCultivationIncomeType
      tags:
      - Misc
      operationId: updateCultivationIncomeType
      deprecated: false
      produces:
      - application/json;charset=UTF-8
      parameters:
      - name: username
        in: header
        required: true
        type: string
        description: ''
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/updateCultivationIncomeTypeRequest'
      responses:
        '422':
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/updateCultivationIncomeType1'
          examples:
            application/json;charset=UTF-8:
              code: Code cannot be updated
          headers:
            Date:
              type: string
              default: Thu, 20 Jul 2023 14:31:58 GMT
            Content-Length:
              type: string
              default: '33'
            Connection:
              type: string
              default: keep-alive
            x-content-type-options:
              type: string
              default: nosniff
            x-xss-protection:
              type: string
              default: 1; mode=block
            cache-control:
              type: string
              default: no-cache, no-store, max-age=0, must-revalidate
            pragma:
              type: string
              default: no-cache
            expires:
              type: string
              default: '0'
            x-frame-options:
              type: string
              default: DENY
            x-envoy-upstream-service-time:
              type: string
              default: '21'
  /AnRkr/cultivationCategoryId/20302:
    get:
      summary: getCultivationIncomeTypeByCultivationCategoryId
      tags:
      - Misc
      operationId: getCultivationIncomeTypeByCultivationCategoryId
      deprecated: false
      produces:
      - application/json
      parameters: []
      responses:
        '204':
          description: No Content
          headers:
            Date:
              type: string
              default: Thu, 20 Jul 2023 14:33:52 GMT
            Connection:
              type: string
              default: keep-alive
            etag:
              type: string
              default: '"0d6d4b3dff6828a0667c336fa89847960"'
            x-content-type-options:
              type: string
              default: nosniff
            x-xss-protection:
              type: string
              default: 1; mode=block
            cache-control:
              type: string
              default: no-cache, no-store, max-age=0, must-revalidate
            pragma:
              type: string
              default: no-cache
            expires:
              type: string
              default: '0'
            x-frame-options:
              type: string
              default: DENY
            x-envoy-upstream-service-time:
              type: string
              default: '13'
definitions:
  addCultivationIncomeTypeRequest:
    title: addCultivationIncomeTypeRequest
    example:
      code: CUL5
      cultivationCategoryId: '20304'
      description: string TEST
      name: string NAME
      status: ACTIVE
    type: object
    properties:
      code:
        type: string
      cultivationCategoryId:
        type: string
      description:
        type: string
      name:
        type: string
      status:
        type: string
    required:
    - code
    - cultivationCategoryId
    - description
    - name
    - status
  addCultivationIncomeType:
    title: addCultivationIncomeType
    example:
      messages: CREATED.
      value: '1888620'
    type: object
    properties:
      messages:
        type: string
      value:
        type: string
    required:
    - messages
    - value
  getAllCultivationIncomeType:
    title: getAllCultivationIncomeType
    example:
      id: 157584
      syncTs: 2022-03-14T03:58:56.602+0000
      version: 3
      tenantId: AnRkr
      code: TTT3
      name: sadd update name
      description: sd update des
      status: ACTIVE
      cultivationCatId: 20302
      cultivationCatCode: CUL1
      cultivationCatName: Cultivation Category 1
      createdUser: lahiru
      createdDate: 2022-02-28T17:20:13.011+0000
      modifiedUser: sashika.jayalath
      modifiedDate: 2022-03-14T03:58:56.601+0000
    type: object
    properties:
      id:
        type: integer
        format: int32
      syncTs:
        type: string
      version:
        type: integer
        format: int32
      tenantId:
        type: string
      code:
        type: string
      name:
        type: string
      description:
        type: string
      status:
        type: string
      cultivationCatId: {}
      cultivationCatCode:
        type: string
      cultivationCatName:
        type: string
      createdUser:
        type: string
      createdDate:
        type: string
      modifiedUser:
        type: string
      modifiedDate:
        type: string
    required:
    - id
    - syncTs
    - version
    - tenantId
    - code
    - name
    - description
    - status
    - cultivationCatId
    - cultivationCatCode
    - cultivationCatName
    - createdUser
    - createdDate
    - modifiedUser
    - modifiedDate
  updateCultivationIncomeTypeRequest:
    title: updateCultivationIncomeTypeRequest
    example:
      code: CUL8
      cultivationCategoryId: '20302'
      description: test
      id: '161351'
      name: test name
      status: ACTIVE
      version: '6'
    type: object
    properties:
      code:
        type: string
      cultivationCategoryId:
        type: string
      description:
        type: string
      id:
        type: string
      name:
        type: string
      status:
        type: string
      version:
        type: string
    required:
    - code
    - cultivationCategoryId
    - description
    - id
    - name
    - status
    - version
  updateCultivationIncomeType1:
    title: updateCultivationIncomeType1
    example:
      code: Code cannot be updated
    type: object
    properties:
      code:
        type: string
    required:
    - code
tags:
- name: Misc
  description: ''
